language: go
sudo: false

go:
  - "1.16.x"
  - "tip"

env:
  - GO111MODULE=on

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -race -v -covermode=atomic -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
